### ISSUE TITLE
PurgeCSS

### ISSUE THREAD

**Issue by gilesbutler** [chrisfrank/nanostyled#2] opened 2019-02-26 20:31 UTC
Hey @chrisfrank,

Awesome idea, I'm just wondering does this work with [PurgeCSS](http://purgecss.com)? A lot of people who use Tailwind use Purge to reduce the outputted CSS' file size significantly. From what I can see with Nanostyled though you might lose some of the benefits of Tailwind as it precompiles your classes into a single classname at the build stage. Then PurgeCSS strips out all the unused classes. The [Extracting Components](https://tailwindcss.com/docs/extracting-components) example in the Tailwind docs explains it a lot better than I can ha. Nanostyled keeps those classes in place though if I'm right? Or does it compile them down to a single classname?

Thanks

**Comment by chrisfrank** [comment] 2019-02-27 00:59
Good question, @gilesbutler. I haven't used the `@apply` directive from Tailwind, but if I'm understanding their docs correctly, it looks like `@apply` and `nanostyled` are two different solutions to the same problem. Could you see yourself using both in the same project?

You're right that Nanostyled doesn't mash long class strings into shorter ones, but that shouldn't matter much for PurgeCSS. Given this document...

```html
<link rel="stylesheet" href="/tailwind.css" />
<button class="bg-blue hover:bg-blue-dark text-white font-bold py-2 px-4 rounded">
  Blue Button
</button>
<button class="bg-red hover:bg-red-dark text-white font-bold py-2 px-4 rounded">
  Red Button
</button>
```

...then PurgeCSS would delete almost the entirety of tailwind.css, because the doc only uses a few selectors. Building a comparable stylesheet via `@apply` might end up organized differently — I imagine it would have fewer selectors and more rules per selector — but I'd be surprised if it turned out significantly smaller.

I'll run a test as soon as I can make time, but if you happen to investigate this before I do, please post the results here. Thanks!

**Comment by gilesbutler** [comment] 2019-02-28 03:29
Thanks for the response @chrisfrank - that's a good point re the output of PurgeCSS. I think you're right, it'd be the same rules just a organised differently. It'd definitely be interesting to compare the results though. I'll let you know if I get a test going.

As for using `@apply` and `nanostyled` together I don't think so but there might be times where you still need to use `@apply`, maybe some global CSS that isn't in components. Or possibly when trying to overwrite styles that come from third party libs.

**Comment by chrisfrank** [comment] 2019-03-05 16:45
@gilesbutler I confirmed today that a nanostyled component works as expected with PurgeCSS, so I'm going to go ahead and close this issue. Please feel free to post again though if you discover that `@apply` churns out CSS that's significantly smaller than nanostyled, though, and thanks for the thoughtful question.

**Closed as completed by chrisfrank** 2019-03-05 16:45 UTC

**Comment by gilesbutler** [comment] 2019-04-17 06:28
Hey @chrisfrank sorry only just seen this! 

Thanks for following up and checking, great result 👍
